version: 2
axioms:
  licensee: license
rules:
  license-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "LICENSE*"
          - "COPYING*"
        nocase: true
  readme-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "README*"
        nocase: true

  contributing-file-exists:
    level: error
    rule:
      type: file-existence
      options:
        globsAny:
          - "docs/"
          - ".github/"
          - "CONTRIB*"
        nocase: true

  readme-references-license:
    level: error
    rule:
      type: file-contents
      options:
        globsAll:
          - "README*"
        content: license
        flags: i

  test-directory-exists:
    level: error
    rule:
      type: directory-existence
      options:
        globsAny:
          - "**/test*"
          - "**/specs"
        nocase: true

  license-detectable-by-licensee:
    level: error
    where: [license=*]
    rule:
      type: license-detectable-by-licensee