# This settings can be used to create repo level settings
repository: 
  # Name of the repo
  name: new-repo-test
 
  # Create the repo if it is not existing
  force_create: true

  # This is the settings that need to be applied to all repositories in the org 
  # See https://developer.github.com/v3/repos/#edit for all available settings for a repository  
  # A short description of the repository that will show up on GitHub
  description: repo description of the repo
  
  # A URL with more information about the repository
  homepage: https://example.repo.io/

  # Either `true` to make the repository private, or `false` to make it public. 
  # If this value is changed and if Org members cannot change the visibility of repos
  # it would result in an error when updating a repo
  private: false
  
  # Can be public or private. If your organization is associated with an enterprise account using 
  # GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal. 
  visibility: private
  
  teams:
  - name: my-new-team
    permission: push
