# This settings can be used to create repo level settings
repository: 
  # Name of the repo
  name: new-repo-test
 
  # Create the repo if it is not existing
  force_create: true

  # This is the settings that need to be applied to all repositories in the org 
  # See https://developer.github.com/v3/repos/#edit for all available settings for a repository  
  # A short description of the repository that will show up on GitHub
  description: repo description of the repo
  
  # A URL with more information about the repository
  homepage: https://example.repo.io/
  
  collaborators:
  - username: nauar
    permission: push
