name: Issue Checklist Workflow
on:
  issues:
    types: [opened]

jobs:
  check_issue_checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check if checkboxes are ticked
        id: check_checkboxes
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue;

            console.log(issue.body)

            const checkboxRegex = /\[ \s* \]/g;
            const checkboxes = issue.body.match(checkboxRegex) || [];
            const requiredCheckboxes = 3; // Modify this with the total number of checkboxes

            let checklistComplete = checkboxes.length === 0;
            console.log(`Checklist complete: ${checklistComplete}`);
            core.setOutput('checklistComplete', checklistComplete);

      - name: Add comment if checklist is not complete
        if: steps.check_checkboxes.outputs.checklistComplete != 'true'
        uses: actions/github-script@v5
        with:
          script: |
            const issue = context.payload.issue;
            const comment = 'Please make sure to check all checkboxes before proceeding.';
            github.issues.createComment({ issue_number: issue.number, owner: context.repo.owner, repo: context.repo.repo, body: comment });
          
      - name: Run the workflow if checklist is complete
        if: steps.check_checkboxes.outputs.checklistComplete == 'true'
        run: |
          # Add your desired commands here to be executed when the checklist is complete
          # For example, you can run a shell script or any other commands
          echo "Checklist is complete! Running additional steps..."
          # Add your additional commands here