---
name: Run repolint
on:
  workflow_dispatch: null
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install -g repolinter
        
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $GITHUB_REPOSITORY_OWNER"
          echo "overridden variable : $RUNNER_OS"
          echo "variable from shell environment : $env_var"
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: ${{ runner.os }}
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: 365344
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Lint Repos
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: scripts/lint-repos.sh
