---
name: Run repolint
on:
  workflow_dispatch: null
  schedule:
    - cron: '*/10 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node for repolinter
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Setup ruby for license checker
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          
      - name: Install dependencies
        run: npm install -g repolinter
        
      - name: Checkout
        uses: actions/checkout@v3  
        
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with:
          app_id: 365344
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Lint Repos
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: repolinter/lint-repos.sh
