name: Run save settings
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: 


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "organization variable : $GITHUB_REPOSITORY_OWNER"
        echo "overridden variable : $RUNNER_OS"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
        ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
        OVERRIDE_VAR: ${{ runner.os }}