name: Run save settings
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: 

   interval: '10m'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          # Get the list of public repositories in the organization
          repositories=$(gh api orgs/<organization>/public_repositories)

          # For each repository, run the script
          for repository in $repositories; do
            echo $repository
          done